services:
  - docker

before_install:
  - chmod +x gradlew

install: true

jobs:
  include:
    - stage: Release to docker
      script:
        - if [ "$TRAVIS_BRANCH" == "release" ]; then
            ./gradlew build;
            ./gradlew releaseDocker -PdockerUsername=$DOCKER_USER -PdockerPassword=$DOCKER_PASSWORD;
          fi